apiVersion: apps/v1
kind: Deployment
metadata:
  name: zz-linux-runner
spec:
  replicas: 1 # change to the desired replica count
  selector:
    matchLabels:
      app: zz-linux-runner
  template:
    metadata:
      labels:
        app: zz-linux-runner
    spec:
      containers:
        - name: zz-linux-runner
          image: daradu/linux-github-runner:2.298.2
          env:
          - name: AZP_URL
            value: "https://dev.azure.com/{org}" # change to use existing org
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-runner-secret
                key: pat
          # resources:
          #   requests:
          #     cpu: 250m
          #     memory: 1G
          #   limits:
          #     cpu: 1000m
          #     memory: 2G
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
